Two fixes for GPKGs with more than 1 XML metadata
Firstly, output a proper error message instead of
TypeError: a bytes-like object is required, not 'list'

Secondly, automatically discard one piece of XML metadata in the case
that both pieces of XML metadata are functionally identical, but one
is original and the other wraps the original in the following manner:

<GDALMultiDomainMetadata>
  <Metadata>
    <MDI key="some_key">
	[ESCAPED_ORIGINAL_XML]
    </MDI>
  </Metadata>
</GDALMultiDomainMetadata>