diff: Fix error diffing WC against commit with a since-deleted dataset
If you delete a dataset, and then attempt to do a diff between a
workingcopy and a commit with that dataset in, `diff` throws an
exception:

```
AttributeError: 'NoneType' object has no attribute 'repo'
```

This change fixes the exception and adds a regression test