Fix tracebacks at test shutdown time
Something to do with holding a partially-completed feature iterator
open, causes SQLAlchemy to dump this traceback at exit:

```
...Results (1.44s):
       1 passed
      32 deselected
Exception during reset or similar
Traceback (most recent call last):
  File "/Users/cdestigter/checkout/sno/sno/ogr_import_source.py", line 653, in features
    yield from self._sqlalchemy_to_sno_features(r)
GeneratorExit
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/cdestigter/checkout/sno/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/cdestigter/checkout/sno/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/cdestigter/checkout/sno/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 559, in do_rollback
    dbapi_connection.rollback()
pysqlite3.dbapi2.ProgrammingError: Cannot operate on a closed database.
```

Merely forcing the feature iterator to be consumed seems to fix it.